apiVersion: v1
kind: ConfigMap
data:
  application.properties: |+
    blobstore.gcs.haya.bucket.name=${BUCKET_NAME}
    blobstore.gcs.haya.import.folder=import
    blobstore.gcs.kakka.bucket.name={{ .Values.gcs.kakka.bucketName }}
    blobstore.gcs.kakka.adminUnits.file=tiamat/geocoder/tiamat_export_geocoder_latest.zip
    blobstore.gcs.moradin.bucket.name={{ .Values.gcs.moradin.bucketName }}
    blobstore.gcs.moradin.latest.filename_without_extension=haya_latest
    blobstore.gcs.moradin.import.folder=import
    spring.profiles.active=gcs-blobstore
    spring.application.name=haya
    spring.main.web-application-type=NONE
    haya.retry.maxAttempts=2
    haya.retry.maxDelay=5000
    haya.retry.backoff.multiplier=3
metadata:
  name: {{ template "haya.name" . }}-config
  namespace: {{ template "haya.name" . }}
  labels:
  {{- include "common.labels" . | indent 4 }}