apiVersion: v1
kind: ConfigMap
data:
  application.properties: |+
    blobstore.gcs.haya.bucket.name=${BUCKET_NAME}
    blobstore.gcs.haya.import.folder=import
    blobstore.gcs.kakka.bucket.name={{ .Values.gcs.kakka.bucketName }}
    blobstore.gcs.kakka.adminUnits.file=tiamat/geocoder/tiamat_export_geocoder_latest.zip
    blobstore.gcs.moradin.bucket.name={{ .Values.gcs.moradin.bucketName }}
    blobstore.gcs.moradin.latest.filename_without_extension=haya_latest
    blobstore.gcs.moradin.import.folder=import
    spring.profiles.active=gcs-blobstore
    management.endpoints.enabled-by-default=false
    management.endpoint.health.enabled=true
    management.health.defaults.enabled=false
    management.endpoint.health.probes.enabled=true
    management.endpoint.health.group.readiness.include=readinessState
    management.endpoints.web.exposure.include=health
    management.endpoints.jmx.exposure.exclude=*
    spring.cloud.task.closecontextEnabled=true
    spring.application.name=haya
    logging.level.org.springframework.cloud.task=DEBUG
metadata:
  name: {{ template "haya.name" . }}-config
  namespace: {{ template "haya.name" . }}
  labels:
  {{- include "common.labels" . | indent 4 }}