apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    {{- include "common.labels" . | indent 4 }}
  name: {{ template "haya.name" . }}
  namespace: {{ template "haya.name" . }}
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: haya
              image: {{ .Values.image.identifier }}
              env:
                - name: JDK_JAVA_OPTIONS
                  value: -server -Xmx{{ .Values.resources.xmx }} -Xss512k -XX:+UseParallelGC -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90
                    -XX:MinHeapFreeRatio=20 -XX:MaxHeapFreeRatio=40 -XX:ActiveProcessorCount={{ .Values.resources.cpuRequest }}
                    -Dspring.config.location=/etc/application-config/application.properties
                    -Dfile.encoding=UTF-8
                - name: TZ
                  value: Europe/Oslo
              envFrom:
                - configMapRef:
                    name: {{ template "haya.name" . }}-bucket
              livenessProbe:
                httpGet:
                  path: /actuator/health/liveness
                  port: {{ .Values.service.http.internalPort }}
                  scheme: HTTP
                initialDelaySeconds: 140
                periodSeconds: 10
                successThreshold: 1
                failureThreshold: 3
                timeoutSeconds: 30
              readinessProbe:
                httpGet:
                  path: /actuator/health/readiness
                  port: {{ .Values.service.http.internalPort }}
                  scheme: HTTP
                initialDelaySeconds: 30
                periodSeconds: 10
                successThreshold: 1
                failureThreshold: 3
                timeoutSeconds: 10
              resources:
                limits:
                  cpu: {{ .Values.resources.cpuLimit }}
                  memory: {{ .Values.resources.memLimit }}
                requests:
                  cpu: {{ .Values.resources.cpuRequest }}
                  memory: {{ .Values.resources.memRequest }}
              volumeMounts:
                - mountPath: /etc/application-config
                  name: application-config
                  readOnly: true
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                    - ALL
                runAsNonRoot: true
                seccompProfile:
                  type: RuntimeDefault
          dnsPolicy: ClusterFirst
          restartPolicy: OnFailure
          schedulerName: default-scheduler
          securityContext:
            runAsGroup: 1000
            runAsNonRoot: true
            runAsUser: 1000
          serviceAccountName: application
          terminationGracePeriodSeconds: 80
          volumes:
            - name: application-config
              configMap:
                defaultMode: 420
                name: {{ template "haya.name" . }}-config
  schedule: {{ .Values.haya.schedule }}
  successfulJobsHistoryLimit: 1