gcp_project = "entur-1287"
gcp_storage_project = "entur-ror-prod"
gcp_resources_project = "entur-ror-prod"
kube_namespace = "production"
bucket_haya_instance_name = "haya-production"
bucket_kakka_instance_name = "kakka-production"