gcp_project = "entur-test-1287"
gcp_storage_project = "entur-ror-test"
gcp_resources_project = "entur-ror-test"
kube_namespace = "staging"
bucket_haya_instance_name = "haya-test"
bucket_kakka_instance_name = "kakka-test"