apiVersion: v1
kind: ConfigMap
data:
  application.properties: |+
    blobstore.gcs.haya.bucket.name={{ .Values.gcp.haya.bucketName }}
    blobstore.gcs.kakka.bucket.name={{ .Values.gcp.kakka.bucketName }}
    blobstore.gcs.kakka.tiamat.geocoder.file=tiamat/geocoder/tiamat_export_geocoder_latest.zip
    haya.update.cron.schedule=0+0+0+1/1+*+?+*
    spring.profiles.active=gcs-blobstore
    management.endpoints.enabled-by-default=false
    management.endpoint.health.enabled=true
    management.health.defaults.enabled=false
    management.endpoint.health.probes.enabled=true
    management.endpoint.health.group.readiness.include=readinessState
    management.endpoints.web.exposure.include=health
    management.endpoints.jmx.exposure.exclude=*
    pelias.stop.place.boost.config={"defaultValue":30, "stopTypeFactors":{"busStation":{"*":2},"metroStation":{"*":2},"railStation":{"*":2}}}
metadata:
  name: {{ template "haya.name" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "common.labels" . | indent 4 }}
